project/urls.py
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path("proposta/<int:id>/", views.proposta, name="proposta"),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

core/models.py
# -*- Mode: Python; coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import admin
from django.contrib.admin.views.main import ChangeList
from django.db import models
from django.db.models import Avg, Sum
from django.utils.html import format_html
from django.utils.safestring import mark_safe
from localflavor.br.br_states import STATE_CHOICES


class Cliente(models.Model):
    nome = models.CharField("Nome", max_length=100)

    def __str__(self):
        return self.nome


class Proposta(models.Model):
    cliente = models.ForeignKey("Cliente", on_delete=models.CASCADE)
    cpf = models.CharField("CPF", blank=True, max_length=14)
    cnpj = models.CharField("CNPJ", blank=True, max_length=18)
    endereco = models.CharField("Endereço", blank=True, max_length=200)
    bairro = models.CharField("Bairro", blank=True, max_length=100)
    cidade = models.CharField("Cidade", blank=True, max_length=100)
    estado = models.CharField(
        max_length=2, null=True, blank=True, choices=STATE_CHOICES
    )
    data = models.DateField("Data de Emissão")
    VALIDADE_CHOICES = (
        ("Quinze", "15 (Quinze)"),
        ("Trinta", "30 (Trinta)"),
        ("Sessenta", "60 (Sessenta)"),
    )

    validade = models.CharField(
        "Validade", blank=True, max_length=200, choices=VALIDADE_CHOICES
    )
    valor = models.DecimalField("Valor a pagar", max_digits=8, decimal_places=2)
    CATEGORY_CHOICES = (
        ("Atrasado", "Atrasado"),
        ("AVencer", "À Vencer"),
        ("Pago", "Pago"),
    )

    situacao = models.CharField("Situação", max_length=200, choices=CATEGORY_CHOICES)
    pago = models.BooleanField(default=False)

    dominio = models.CharField(
        "Dominio do Site",
        blank=True,
        max_length=200,
        help_text="URL - exe: seudominio.com.br",
    )
    dominio_login = models.CharField(
        "Acesso ao Admin",
        max_length=200,
        blank=True,
        help_text="URL - exe: seudominio.com.br/admin",
    )
    login = models.CharField("Login", max_length=30, blank=True)
    senha = models.CharField("Senha", max_length=30, blank=True)

    def imprimir(self):
        return mark_safe(
            """<a href=\"/proposta/%s/\" target="_blank"><img src=\"/static/images/b_print.png\"></a>"""
            % self.id
        )

    class Meta:
        ordering = ["-data"]
        verbose_name = "Proposta"
        verbose_name_plural = "Propostas"

    def __str__(self):
        if self.cliente.nome:
            return self.cliente.nome
        else:
            return self.custom_alias_name

core/views.py
from django.shortcuts import render

# Create your views here.

project/views.py
from core.models import Cliente, Proposta
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render


# Proposta
@login_required(redirect_field_name="redirect_to")
def proposta(request, id=None, *args, **kwargs):
    contexto = {}
    contexto["proposta_base"] = Proposta.objects.get(id=id)

    return render(request, "proposta.html", contexto)

templates/proposta.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>PROPOSTA - {{ proposta_base.cliente.nome }} - {{ proposta_base.data|date:"d F Y" }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/style-proposta.css' %}">
</head>

<body>
    <div id="geral">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-12">
                    <div class="img-logo">
                        <img src="{% static 'images/logo.png' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-12">
                    <div class="topo center">
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <h3><strong>CONTRATO DE PRESTAÇÃO DE SERVIÇO DE WEBSITE</strong></h3>
                        <h4>MAP Systems - CNPJ: 00.000.000/0000-00</h4>
                        <p>Av. Aldino Pinotti, 500 - Centro - Fone: 011-953-038-500 <br>
                            Site: www.mapsystems.com / Email: contato@mapsystems.com
                            <br>São Bernardo do Campo - São Paulo</p>

                    </div>
                </div>
            </div>
            <div class="row">
                <hr>
                <div class="informacao-cliente">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <p> <strong>EMPRESA OU CLIENTE:</strong> {{ proposta_base.cliente.nome|upper }}</p>
                        {% if proposta_base.cpf %}
                        <p> <strong>CPF:</strong> {{ proposta_base.cpf }}</p>
                        {% else %}
                        <p> <strong>CNPJ:</strong> {{ proposta_base.cnpj }}</p>
                        {% endif %}
                        <p> <strong>ENDEREÇO:</strong> {{ proposta_base.endereco|upper }}</p>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <p> <strong>BAIRRO:</strong> {{ proposta_base.bairro|upper }}</p>
                        <p> <strong>CIDADE:</strong> {{ proposta_base.cidade|upper }}</p>
                        <p> <strong>ESTADO:</strong> {{ proposta_base.get_estado_display|upper  }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row"><br>
                <hr>
                <strong>I – DO OBJETO DO CONTRATO</strong><br>

                O presente contrato tem como objeto a formulação do conjunto de páginas eletrônicas e gráficas, aqui
                denominado simplesmente por” SITE” ou "HOME PAGE", para uso exclusivo na Internet, com referência
                institucionais da CONTRATANTE, demostrando os seus produtos, serviços e tecnologia. Também incluso a
                prestação de serviço referente a manutenção deste “SITE”<br>
                <hr>
                <strong>II - DAS OBRIGAÇÕES DA CONTRATADA</strong><br>


                A CONTRATRADA se obriga a desenvolver o objeto deste contrato da maneira mais adequada e dinâmica, dando
                ênfase a marca e a qualidade dos produtos e serviços da CONTRATANTE.
                Faz parte ainda os seguintes serviços a serem executados pela CONTRATADA:<br>
                <p class="espaco">
                    - Elaboração do projeto gráfico e fluxo das informações;<br>
                    - Programação das páginas em HTML, CSS, JQUERY, JAVA SCRIPT;<br>
                    - Programação das páginas em PYTHON E DJANGO;<br>
                    - Programação dos bancos de dados necessários;<br>
                    - Manutenção do “SITE” assim que as partes acharem necessário.<br>
                </p>
                <hr>
                <strong>III - DAS OBRIGAÇÕES DO CONTRATANTE</strong><br>


                Ficará sobre responsabilidade da CONTRATANTE, a entrega de todo o material necessário para execução dos
                trabalhos ora tais como: <br>
                <p class="espaco">
                    - Fotos e imagens a serem adicionadas nas páginas;<br>
                    - Textos descritivos;<br>
                    - Logotipo.<br>
                    - Vídeos <br>
                </p>
                O CONTRATANTE deverá efetuar corretamente os pagamentos à CONTRATADA, segundo item V.
                <hr>
                <strong>IV - DA MANUTENÇÃO DOS SERVIÇOS</strong><br>

                A CONTRATADA através da manutenção dos serviços, sendo Preventivo e/ou Corretivo, manterá o “SITE” em
                condições de navegabilidade, efetuando os necessários ajustes, configurações e reparos visuais.<br>

                1º. somente os técnicos da CONTRATADA poderão executar serviços técnicos preventivos e ou corretivos, a
                que se refere esta cláusula.<br>

                2º. As manutenções dos serviços aqui contratados não incluem: <br>
                <p class="espaco">
                    - Os serviços adicionais aos mencionados neste contrato;<br>
                    - Elaboração e construção de bancos de dados extras;<br>
                    - Produção de fotos;<br>
                    - Produção de vídeos;<br>
                </p>

                3º. A CONTRATADA se compromete a cadastrar o "SITE" do CONTRATANTE nos principais "SITES" de busca
                nacionais e internacionais.<br>

                4º. A CONTRATADA, se compromete a hospedagem de 6 meses (seis meses) de hospedagem grátis, a pois o
                termino dos 6 meses.<br>
                Será cobrado o valor da hospedagem da seguinte forma que o cliente desejar.<br>
                <p class="espaco">
                    <b>Mensal</b> de R$ 50,00 (Setenta reais)<br>
                    <b>Trimensal</b> de R$ 150,00 - (Duzentos e dez reais)<br>
                    <b>Semestral</b> de R$ 300,00 - (Quatrocentos e vinte reais)<br>
                    <b>Anual</b> de R$ 600,00 - (Oitocentos e quarenta reais)<br>
                </p>
                A pois a escolha DA CONTRATADA, a respeito do pagamento do servidor, será atualizado no banco de dados,
                para que o mesmo seja efetuado automaticamente 05 dias úteis antes do vencimento.<br>

                <hr>
                <strong>V - PREÇO E FORMA DE PAGAMENTO</strong><br>

                Para os serviços de construção, manutenção e inclusão do “SITE”, objeto deste contrato, ora estipulado
                terá um custo no valor de:<br>
                - Construção: <b>R$ {{proposta_base.valor}}</b> <br>

                - Uma vez que a CONTRATADA cumpra todos os requisitos, o CONTRATANTE efetuará o pagamento do serviço
                prestado de construção do “SITE” da seguinte forma:<br>
                <p class="espaco">
                    {% for item_da_proposta in proposta_base.pagamento_set.all %}

                    - <b>R$</b> {{item_da_proposta.valor}} <b>( {{item_da_proposta.valor_extenso|capfirst|upper}} )</b>,
                    {{item_da_proposta.descricao|capfirst}}.<br>
                    {% endfor %}
                </p>
                <hr>
                <strong>VI - DA RESCISÃO DO CONTRATUAL</strong><br>

                O presente contrato poderá ser rescindido pelo CONTRATANTE, sem ônus algum, quando:<br>
                - A CONTRATADA não executar os serviços solicitados pelo CONTRATANTE, e que estejam de acordo com as
                cláusulas deste contrato.<br>

                - Quando a CONTRATADA descumprir alguma das cláusulas deste contrato.
                O presente contrato poderá ser rescindido pela CONTRATADA, quando:<br>

                - O CONTRATANTE na hipótese de inadimplência das obrigações ora assumidas, devendo a parte inocente
                notificar a parte culpada à sanar sua falha no prazo de 30 dias, após isso, não sanada a dívida, a
                CONTRATADA não efetuará qualquer tipo de trabalho para o CONTRATANTE.<br>
                <hr>
                <strong>VII - PRAZO DE VIGÊNCIA DO PRESENTE CONTRATO</strong><br>

                Com exceção dos serviços de implantação do sistema o presente contrato vigorará por prazo determinado de
                1 (um) ano, podendo ser renovado posteriormente.

                E, por assim estarem justos e contratados, firmam o presente contrato em duas vias de igual teor e
                forma.<br>
                <hr>
                <strong>VIII – DADOS DO SITE E ADMINISTRAÇÃO</strong><br>

                Para acesso a administração do site segue a baixo o site, loguin e senha.<br>

                <b>DOMINIO:</b> www.{{proposta_base.dominio}}<br>
                <b>DOMINIO ADMIN:</b> www.{{proposta_base.dominio}}/{{proposta_base.dominio_loguin}}<br>
                <b>LOGUIN:</b> {{proposta_base.loguin}}<br>
                <b>SENHA:</b> {{proposta_base.senha}}<br>
                <b>BANCO DE DADOS:</b> {{proposta_base.loguin}}<br>
                <b>SERVIDOR:</b> MAP Systems – DigitalOcean USA<br><br>

                <i>Obs. a senha informada para cada um dos itens acima pode ser modificada, por qualquer outra
                    senha.</i><br>
                <hr>
                <strong>IX – SERVIÇOS DE EMAIL’S</strong><br>

                <b>EMAIL:</b> email.{{proposta_base.dominio}}<br>
                <b>USUÁRIO ADMIN:</b> contato@{{proposta_base.dominio}}<br>
                <b>SENHA ADMIN:</b> @{{proposta_base.senha}}<br><br>

                <i>Obs. a senha informada para cada um dos itens acima pode ser modificada, por qualquer outra
                    senha.</i><br><br>

                Poderão ser criadas até 10(dez) contas de E-mails capacidade de 5GB de armazenamentos. As criações de
                e-mails podem ser feitas através do e-mail principal
                <b>contato@{{proposta_base.dominio}}</b>
                Onde o Administrador pode adicionar, remover, bloquear, editar e excluir.<br>

                <hr>
                <strong><i>Nota: À MAP Systems, tem total Sigilo com dados do seu cliente, se de fato o cliente,
                        esquecer a senha, ou loguin. Você pode entrar em contato conosco, através de telefone ou E-mail.
                        À MAP Systems, também dá treinamento para que o cliente mesmo possa está atualizando seu
                        próprio Website.</i></strong>
                <br>
                <hr>
                <div class="validade"><i></i>Proposta válida por {{ proposta_base.get_validade_display }} dias</div><br>

                <div class="infor-data">São Bernardo do Campo - SP - {{ proposta_base.data|date|upper }}</div></b><br>

                <div class="separador text-center">
                    <br>
                    <br>
                    <br>

                    _________________________________________ <br>
                    MAP Systems <br>
                    <p>CNPJ: 00.000.000/0000-00</p>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>

                    _________________________________________<br>
                    {{proposta_base.cliente.nome}}<br>
                    {% if proposta_base.cpf %}
                    <p>CPF: {{ proposta_base.cpf }}</p>
                    {% else %}
                    <p>CNPJ: {{ proposta_base.cnpj }}</p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</body>

</html>